language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_script:
  - echo 'date.timezone = "Europe/Berlin"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer update

script:
  - phpunit

notifications:
  email:
    -  sebastian.kuhnow@gmail.com
