language: php

php:
    - 5.5
    - 5.6
    - 7.0

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer self-update
  - composer install

script:
  - phpunit

notifications:
  email:
    -  sebastian.kuhnow@gmail.com