imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: de
    page_title: Pagetitle

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form_themes: ['bootstrap_3_layout.html.twig']
    globals:
        page_title: '%page_title%'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        charset:  UTF8
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# app/config/config.yml
fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User

sonata_block:
    default_contexts: [cms]
    blocks:
        # enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts: [admin]

assetic:
    debug:          '%kernel.debug%'
    use_controller: '%kernel.debug%'
    filters:
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Compressed'
        jsqueeze: ~
    assets:
        glyphicons-halflings-regular-eot:
            inputs: '%kernel.root_dir%/Resources/assets/fonts/glyphicons-halflings-regular.eot'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.eot'
        glyphicons-halflings-regular-svg:
            inputs: '%kernel.root_dir%/Resources/assets/fonts/glyphicons-halflings-regular.svg'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.svg'
        glyphicons-halflings-regular-ttf:
            inputs: '%kernel.root_dir%/Resources/assets/fonts/glyphicons-halflings-regular.ttf'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.ttf'
        glyphicons-halflings-regular-woff:
            inputs: '%kernel.root_dir%/Resources/assets/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.woff'
        glyphicons-halflings-regular-woff2:
            inputs: '%kernel.root_dir%/Resources/assets/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/bootstrap/glyphicons-halflings-regular.woff2'

liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        cache: ~
        thumbnail:
            quality: 75
            filters:
                thumbnail: { size : [500, 376], mode : outbound }
                # 4px larger to create a 2px border around the final image
                background: { size : [504, 380], position : center, color : '#000000' }
